<a href="https://colab.research.google.com/github/shahab271069/Advanced-Time-series-analysis/blob/main/Python_third_session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python Packages
In this notebook, we will explore several essential Python packages used for various tasks, including file handling, numerical computations, data manipulation, and visualization.

## Table of Contents
- [OS](#os)
- [Glob](#glob)
- [NumPy](#numpy)
- [SciPy](#scipy)
- [Matplotlib](#matplotlib)
- [Pandas](#pandas)


## OS
The `os` module provides a way of using operating system-dependent functionality like reading or writing to the file system. It allows you to interact with the file system in a platform-independent manner.

### Features:
- File and directory manipulation
- Environment variables
- Process management

### Examples:

In [1]:
import os

# Example 1: Get current working directory
current_directory = os.getcwd()
current_directory

'/content'

In [2]:
# Example 2: List files in the current directory
files = os.listdir(current_directory)
files

['.config', 'sample_data']

In [3]:
# Example 3: Create a new directory
new_directory = os.path.join(current_directory, 'new_folder')
os.makedirs(new_directory, exist_ok=True)
new_directory

'/content/new_folder'

In [4]:
# Example 3: Create a new directory
new_directory = os.path.join(current_directory, 'new_folder')
os.mkdir(new_directory)
new_directory

FileExistsError: [Errno 17] File exists: '/content/new_folder'

In [5]:
# Example 4: Remove a directory
os.rmdir(new_directory)  # Ensure the directory is empty before removing it


In [6]:
# Example 5: Get environment variables
env_vars = os.environ
env_vars

environ{'SHELL': '/bin/bash',
        'NV_LIBCUBLAS_VERSION': '12.2.5.6-1',
        'NVIDIA_VISIBLE_DEVICES': 'all',
        'COLAB_JUPYTER_TRANSPORT': 'ipc',
        'NV_NVML_DEV_VERSION': '12.2.140-1',
        'NV_CUDNN_PACKAGE_NAME': 'libcudnn8',
        'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
        'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.19.3-1+cuda12.2',
        'NV_LIBNCCL_DEV_PACKAGE_VERSION': '2.19.3-1',
        'VM_GCE_METADATA_HOST': '169.254.169.253',
        'HOSTNAME': 'ad8ca39acfa3',
        'LANGUAGE': 'en_US',
        'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
        'COLAB_TPU_1VM': '',
        'GCE_METADATA_TIMEOUT': '3',
        'NVIDIA_REQUIRE_CUDA': 'cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>

In [7]:
# Example 3: Create a new directory
new_directory = os.path.join(current_directory, 'new_folder')
os.makedirs(new_directory, exist_ok=True)
new_directory

'/content/new_folder'

In [8]:
# How change directories
%cd new_folder

/content/new_folder


In [10]:
# Example 1: Get current working directory
current_directory = os.getcwd()
current_directory

'/content/new_folder'

In [11]:
for i in range(10):
    os.mkdir(f'dir{i}')

## Glob
The `glob` module finds all the pathnames matching a specified pattern according to the rules used by the Unix shell. It is useful for file searching.

### Features:
- Pattern matching for file names
- Supports wildcards

### Examples:

In [13]:
!git clone https://github.com/numpy/numpy

Cloning into 'numpy'...
remote: Enumerating objects: 282430, done.
remote: Counting objects: 100% (1220/1220), done.
remote: Compressing objects: 100% (599/599), done.
remote: Total 282430 (delta 783), reused 955 (delta 614), pack-reused 281210 (from 1)
Receiving objects: 100% (282430/282430), 144.91 MiB | 20.65 MiB/s, done.
Resolving deltas: 100% (223073/223073), done.


In [15]:
import glob

# Example 1: Find all Python files
py_files = glob.glob('./numpy/*.py')
py_files

['./numpy/pavement.py']

In [16]:
# Example 2: Find all text files in a directory
txt_files = glob.glob('*.txt')
txt_files

[]

In [17]:
# Example 3: Find files with a specific pattern
pattern_files = glob.glob('data/*.csv')
pattern_files

[]

In [22]:
# Example 4: Using recursive search
all_py_files = glob.glob('**/*M*.py', recursive=True)
all_py_files

['numpy/tools/swig/test/testMatrix.py']

In [23]:
# Example 5: Find all JPEG images
jpeg_files = glob.glob('*.jpeg')
jpeg_files

[]

## NumPy
NumPy is the fundamental package for numerical computations in Python. It provides support for arrays, matrices, and many mathematical functions.

### Features:
- N-dimensional arrays
- Mathematical functions
- Linear algebra routines

### Examples:

In [1]:
import numpy as np

# Example 1: Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
array_1d

array([1, 2, 3, 4, 5])

In [25]:
# Example 2: Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Example 3: Compute the mean of an array
mean_value = np.mean(array_1d)
mean_value

3.0

In [27]:
# Example 4: Compute the mean of an 2d-array
mean_value = np.mean(array_2d)
mean_value

3.5

In [28]:
# Example 5: Compute the mean of an 2d-array in each column
mean_value = np.mean(array_2d, axis=1)
mean_value

array([2., 5.])

In [29]:
# Example 6: Compute the mean of an 2d-array in each row
mean_value = np.mean(array_2d, axis=0)
mean_value

array([2.5, 3.5, 4.5])

In [32]:
# Example 7: Compute the median of an 2d-array in each column
median_value = np.median(array_2d, axis=1)
median_value

array([2., 5.])

In [31]:
# Example 8: Compute the median of an 2d-array in each row
median_value = np.median(array_2d, axis=0)
median_value

array([2.5, 3.5, 4.5])

In [34]:
# Example 10: Create a 2D array
array_2d = np.array([[1, 2, 3, 5, 10, 15, 20], [4, 5, 6, 30, 50, 21, 40], [5, 8, 12, 70, 51, 29, 78]])
array_2d

array([[ 1,  2,  3,  5, 10, 15, 20],
       [ 4,  5,  6, 30, 50, 21, 40],
       [ 5,  8, 12, 70, 51, 29, 78]])

In [36]:
# How to know what is the matrix or array shape (row, column, ...)
array_2d.shape

(3, 7)

In [37]:
# Example 11: Compute the mean and median of an 2d-array in each row
mean_value = np.mean(array_2d, axis=0)
median_value = np.median(array_2d, axis=0)
mean_value, median_value

(array([ 3.33333333,  5.        ,  7.        , 35.        , 37.        ,
        21.66666667, 46.        ]),
 array([ 4.,  5.,  6., 30., 50., 21., 40.]))

In [39]:
# Example 11: Compute the mean and median of an 2d-array in each column
mean_value = np.mean(array_2d, axis=1)
median_value = np.median(array_2d, axis=1)
mean_value, median_value

(array([ 8.        , 22.28571429, 36.14285714]), array([ 5., 21., 29.]))

In [40]:
# Example 12: Perform element-wise addition
array_added = array_1d + 10
array_added

array([11, 12, 13, 14, 15])

In [41]:
# Example 13: Perform element-wise addition based on the array
array_added = array_1d + array_1d
array_added

array([ 2,  4,  6,  8, 10])

In [42]:
# Example 14: Reshape an array
reshaped_array = array_2d.reshape((7, 3))
reshaped_array

array([[ 1,  2,  3],
       [ 5, 10, 15],
       [20,  4,  5],
       [ 6, 30, 50],
       [21, 40,  5],
       [ 8, 12, 70],
       [51, 29, 78]])

In [43]:
# Example 15: Transformation
reshaped_array = array_2d.T
reshaped_array

array([[ 1,  4,  5],
       [ 2,  5,  8],
       [ 3,  6, 12],
       [ 5, 30, 70],
       [10, 50, 51],
       [15, 21, 29],
       [20, 40, 78]])

In [44]:
# Example 16: Slicing data
array_2d[:2,3:]

array([[ 5, 10, 15, 20],
       [30, 50, 21, 40]])

In [45]:
# Example 17: number of dimension
array_2d.ndim

2

In [46]:
# Example 18: size of the data
array_2d.size

21

In [47]:
# Example 19: NAN values
array_2d = np.array([[1, 2, 3, 5, 10, 15, 20], [4, 5, np.nan, 30, 50, 21, 40], [5, 8, 12, 70, 51, 29, 78]])
array_2d

array([[ 1.,  2.,  3.,  5., 10., 15., 20.],
       [ 4.,  5., nan, 30., 50., 21., 40.],
       [ 5.,  8., 12., 70., 51., 29., 78.]])

In [48]:
# Example 20: Make a zeros array
array_2d = np.zeros((3,7))
array_2d

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [49]:
# Example 21: Make a ones array
array_2d = np.ones((3,7))
array_2d

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [50]:
# Example 22: Make a two array
array_2d = 2*np.ones((3,7))
array_2d

array([[2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2.]])

In [54]:
# Example 23: Make an range data
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
# Example 24: Make a range data with step
array_1d = np.arange(0,11,2)
array_1d

array([ 0,  2,  4,  6,  8, 10])

In [56]:
# documentation of a command
?np.arange

In [61]:
# Example 25: Make a data with specific number
array_1d = np.linspace(0,1,9)
array_1d

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [62]:
array_1d.shape

(9,)

In [63]:
# Example 26: Make a data with specific number
array_1d = np.linspace(0,1,10)
array_1d

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [64]:
# Example 27: Make a data with specific number
array_1d = np.linspace(10,100,10)
array_1d

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [66]:
# Example 28: Lograrithmic array
array_1d = np.logspace(2,10,10)
array_1d

array([1.00000000e+02, 7.74263683e+02, 5.99484250e+03, 4.64158883e+04,
       3.59381366e+05, 2.78255940e+06, 2.15443469e+07, 1.66810054e+08,
       1.29154967e+09, 1.00000000e+10])

In [70]:
# Example 29: exponential function
array_1d = np.linspace(10,100,10)
array_1d = np.exp(array_1d)
array_1d

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.14200739e+26, 2.51543867e+30, 5.54062238e+34,
       1.22040329e+39, 2.68811714e+43])

In [72]:
# Example 30: logarithmic function
array_1d = np.linspace(10,1000,10)
array_1d = np.log(array_1d)
array_1d

array([2.30258509, 4.78749174, 5.43807931, 5.82894562, 6.10924758,
       6.32793678, 6.50727771, 6.65929392, 6.79122146, 6.90775528])

In [73]:
# Example 31: sorting data
array_1d = [10,20,10, 30, 21, 51, 11]
array_1d = np.sort(array_1d)
array_1d

array([10, 10, 11, 20, 21, 30, 51])

In [74]:
# Example 32: unique values
array_1d = [10,20,10, 30, 21, 51, 11]
array_1d = np.unique(array_1d)
array_1d

array([10, 11, 20, 21, 30, 51])

In [77]:
# Example 33: concantenate array
array_1d = [10,20,10, 30, 21, 51, 11]
array_1_second = [1,2,5, 3, 2, 5, 21]
array_1d = np.concatenate([array_1d,array_1_second])
array_1d

array([10, 20, 10, 30, 21, 51, 11,  1,  2,  5,  3,  2,  5, 21])

In [84]:
# Example 34: create a new axis
array_1d = np.array([10,20,10, 30, 21, 51, 11])
array_1d[np.newaxis,:].shape

(1, 7)

In [85]:
# Example 34: filtering data
array_1d = np.array([10,20,10, 30, 21, 51, 11])
array_1d[array_1d<50]

array([10, 20, 10, 30, 21, 11])

In [86]:
array_1d<50

array([ True,  True,  True,  True,  True, False,  True])

In [87]:
# Example 35: finding max, min, average, and so on
array_1d = np.array([10,20,10, 30, 21, 51, 11])
array_1d.min(), array_1d.max(), array_1d.mean()

(10, 51, 21.857142857142858)

In [89]:
# Example 36: finding max, min, average on 2d array row wise
array_2d = np.array([[1, 2, 3, 5, 10, 15, 20], [4, 5, 10, 30, 50, 21, 40], [5, 8, 12, 70, 51, 29, 78]])

array_2d.min(), array_2d.max(), array_2d.mean()

(1, 78, 22.333333333333332)

In [90]:
# Example 37: finding max, min, average on 2d array column wise
array_2d = np.array([[1, 2, 3, 5, 10, 15, 20], [4, 5, 10, 30, 50, 21, 40], [5, 8, 12, 70, 51, 29, 78]])

array_2d.min(axis=1), array_2d.max(axis=1), array_2d.mean(axis=1)

(array([1, 4, 5]),
 array([20, 50, 78]),
 array([ 8.        , 22.85714286, 36.14285714]))

In [91]:
# Example 38: flatten you data
array_2d = np.array([[1, 2, 3, 5, 10, 15, 20], [4, 5, 10, 30, 50, 21, 40], [5, 8, 12, 70, 51, 29, 78]])
array_2d.flatten()

array([ 1,  2,  3,  5, 10, 15, 20,  4,  5, 10, 30, 50, 21, 40,  5,  8, 12,
       70, 51, 29, 78])

In [93]:
# Example 39: save your array
array_2d = np.array([[1, 2, 3, 5, 10, 15, 20], [4, 5, 10, 30, 50, 21, 40], [5, 8, 12, 70, 51, 29, 78]])
np.save('array_2d.npy', array_2d)

In [2]:
# Example 40: save your big array (efficient and fast)
array_2d = np.linspace(0,1e5, 100000)
np.save('array_2d.npy', array_2d)

## SciPy
SciPy is an open-source library used for scientific and technical computing. It builds on NumPy and provides additional functionality.

### Features:
- Optimization
- Integration
- Interpolation

### Examples:

In [6]:
# An easy way to introduce a funcion
equation = lambda x: (x-2)**2

def equation_second(x):

    return (x-2)**2

In [9]:
from scipy import optimize

# Example 1: Minimize a simple function
result = optimize.minimize(equation_second, 0,method ='L-BFGS-B')
result

  message: CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL
  success: True
   status: 0
      fun: 1.1082019140377291e-18
        x: [ 2.000e+00]
      nit: 2
      jac: [ 1.211e-08]
     nfev: 6
     njev: 3
 hess_inv: <1x1 LbfgsInvHessProduct with dtype=float64>

In [10]:
from scipy import optimize

# Example 2: Minimize a simple function
result = optimize.minimize(equation_second, 0,method ='Nelder-Mead')
result

       message: Optimization terminated successfully.
       success: True
        status: 0
           fun: 4.930380657631324e-30
             x: [ 2.000e+00]
           nit: 27
          nfev: 54
 final_simplex: (array([[ 2.000e+00],
                       [ 2.000e+00]]), array([ 4.930e-30,  3.906e-09]))

In [11]:
# Example 3: Solve a linear equation
from scipy.linalg import solve
# A = A[0,0]*x+A[0,1]*y this is the equation
# A = {3*x+y=9, x+2*y=8}
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
solution = solve(A, b)
solution

array([2., 3.])

In [12]:
# Example 4: Solve a linear equation
from scipy.linalg import solve
# A = A[0,0]*x+A[0,1]*y this is the equation
# A = {10*x+5*y=1, 8*x+9*y=25}
A = np.array([[10, 5], [8, 9]])
b = np.array([1, 25])
solution = solve(A, b)
solution

array([-2.32,  4.84])

In [13]:
# Example 5: Perform integration
from scipy.integrate import quad
integral_result, _ = quad(lambda x: x**2, 0, 1)
integral_result

0.33333333333333337

In [15]:
# Example 6: Perform integration of two-d equation
from scipy.integrate import  dblquad
f = lambda y, x: x*y**2
integral_result, _ = dblquad(f, 0, 1, 0, 5)
integral_result

20.833333333333336

In [17]:
# Example 7: Interpolate data with linear
from scipy.interpolate import interp1d
x = np.array([0, 1, 2, 3])
y = np.array([0, 1, 4, 9])
f = interp1d(x, y, kind='linear')
interpolated_value = f(1.5)
interpolated_value

array(2.5)

In [18]:
# Example 8: Interpolate data with quadratic
from scipy.interpolate import interp1d
x = np.array([0, 1, 2, 3])
y = np.array([0, 1, 4, 9])
f = interp1d(x, y, kind='quadratic')
interpolated_value = f(1.5)
interpolated_value

array(2.25)

In [19]:
# Example 8: Interpolate data with cubic
from scipy.interpolate import interp1d
x = np.array([0, 1, 2, 3])
y = np.array([0, 1, 4, 9])
f = interp1d(x, y, kind='cubic')
interpolated_value = f(1.5)
interpolated_value

array(2.25)

In [20]:
# Example 9: Interpolate data with nearest
from scipy.interpolate import interp1d
x = np.array([0, 1, 2, 3])
y = np.array([0, 1, 4, 9])
f = interp1d(x, y, kind='nearest')
interpolated_value = f(1.5)
interpolated_value

array(1.)

In [22]:
# Example 10: Interpolate data with nearest
from scipy.interpolate import interp2d
x = np.array([0, 1, 2, 3])
y = np.array([0, 1, 4, 9])
z = np.array([0, 5, 6, 12])
f = interp2d(x, y, z, kind='linear')
interpolated_value = f(1.5,2)
interpolated_value

<ipython-input-22-ebce12617a0a>:6: DeprecationWarning: `interp2d` is deprecated in SciPy 1.10 and will be removed in SciPy 1.14.0.

For legacy code, nearly bug-for-bug compatible replacements are
`RectBivariateSpline` on regular grids, and `bisplrep`/`bisplev` for
scattered 2D data.

In new code, for regular grids use `RegularGridInterpolator` instead.
For scattered data, prefer `LinearNDInterpolator` or
`CloughTocher2DInterpolator`.

For more details see
`https://scipy.github.io/devdocs/notebooks/interp_transition_guide.html`

  f = interp2d(x, y, z, kind='linear')
<ipython-input-22-ebce12617a0a>:7: DeprecationWarning: `interp2d` is deprecated in SciPy 1.10 and will be removed in SciPy 1.14.0.

For legacy code, nearly bug-for-bug compatible replacements are
`RectBivariateSpline` on regular grids, and `bisplrep`/`bisplev` for
scattered 2D data.

In new code, for regular grids use `RegularGridInterpolator` instead.
For scattered data, prefer `LinearNDInterpolator` or
`CloughTocher2DInte

array([6.5])

In [ ]:
# Example 5: Generate a Gaussian distribution
from scipy.stats import norm
data = norm.rvs(size=1000)
data

## Matplotlib
Matplotlib is a plotting library for the Python programming language and its numerical mathematics extension, NumPy. It provides an object-oriented API for embedding plots into applications.

### Features:
- 2D plotting
- Interactive plots
- Customizable visualizations

### Examples:

In [ ]:
import matplotlib.pyplot as plt

# Example 1: Basic line plot
plt.plot([1, 2, 3, 4], [1, 4, 9, 16])
plt.title('Basic Line Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()

In [ ]:
# Example 2: Scatter plot
plt.scatter([1, 2, 3, 4], [1, 4, 9, 16])
plt.title('Scatter Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.show()

In [ ]:
# Example 3: Bar chart
plt.bar(['A', 'B', 'C', 'D'], [3, 7, 5, 6])
plt.title('Bar Chart')
plt.xlabel('Categories')
plt.ylabel('Values')
plt.show()

In [ ]:
# Example 4: Histogram
data = np.random.randn(1000)
plt.hist(data, bins=30)
plt.title('Histogram')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()

In [ ]:
# Example 5: Pie chart
sizes = [15, 30, 45, 10]
plt.pie(sizes, labels=['A', 'B', 'C', 'D'], autopct='%1.1f%%')
plt.title('Pie Chart')
plt.show()

## Pandas
Pandas is a powerful data manipulation and analysis library for Python. It provides data structures like Series and DataFrames to handle and analyze data efficiently.

### Features:
- Data manipulation with DataFrames
- Flexible data handling
- Time series support

### Examples:

In [ ]:
import pandas as pd

# Example 1: Create a DataFrame
data = {'Column1': [1, 2, 3], 'Column2': [4, 5, 6]}
df = pd.DataFrame(data)
df

In [ ]:
# Example 2: Read CSV file
# df_from_csv = pd.read_csv('file.csv')  # Uncomment to read a CSV file
# df_from_csv

In [ ]:
# Example 3: DataFrame operations
df['Column3'] = df['Column1'] + df['Column2']
df

In [ ]:
# Example 4: Group by operation
grouped = df.groupby('Column1').sum()
grouped

In [ ]:
# Example 5: Handling missing values
df_with_nan = df.copy()
df_with_nan.loc[1, 'Column2'] = None
df_filled = df_with_nan.fillna(0)
df_filled